// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TruckingService.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Expero {

  /// <summary>Holder for reflection information generated from TruckingService.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class TruckingServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for TruckingService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TruckingServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVUcnVja2luZ1NlcnZpY2UucHJvdG8SBmV4cGVybyJtCgVQb2ludBISCgp0",
            "cnVja19uYW1lGAEgASgJEhoKEnRydWNrX21hbnVmYWN0dXJlchgCIAEoCRIP",
            "Cgd0cmlwX2lkGAMgASgJEhAKCGxhdGl0dWRlGAQgASgCEhEKCWxvbmdpdHVk",
            "ZRgFIAEoAiIaCghSZXNwb25zZRIOCgZzdGF0dXMYASABKAUiGgoDTXNnEhMK",
            "C2hlbGxvX3dvcmxkGAEgASgJMmQKCFRydWNraW5nEjUKDlJlY29yZExvY2F0",
            "aW9uEg0uZXhwZXJvLlBvaW50GhAuZXhwZXJvLlJlc3BvbnNlKAEwARIhCgVI",
            "ZWxsbxILLmV4cGVyby5Nc2caCy5leHBlcm8uTXNnYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedCodeInfo(null, new pbr::GeneratedCodeInfo[] {
            new pbr::GeneratedCodeInfo(typeof(global::Expero.Point), global::Expero.Point.Parser, new[]{ "TruckName", "TruckManufacturer", "TripId", "Latitude", "Longitude" }, null, null, null),
            new pbr::GeneratedCodeInfo(typeof(global::Expero.Response), global::Expero.Response.Parser, new[]{ "Status" }, null, null, null),
            new pbr::GeneratedCodeInfo(typeof(global::Expero.Msg), global::Expero.Msg.Parser, new[]{ "HelloWorld" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Point : pb::IMessage<Point> {
    private static readonly pb::MessageParser<Point> _parser = new pb::MessageParser<Point>(() => new Point());
    public static pb::MessageParser<Point> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Expero.TruckingServiceReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Point() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Point(Point other) : this() {
      truckName_ = other.truckName_;
      truckManufacturer_ = other.truckManufacturer_;
      tripId_ = other.tripId_;
      latitude_ = other.latitude_;
      longitude_ = other.longitude_;
    }

    public Point Clone() {
      return new Point(this);
    }

    /// <summary>Field number for the "truck_name" field.</summary>
    public const int TruckNameFieldNumber = 1;
    private string truckName_ = "";
    public string TruckName {
      get { return truckName_; }
      set {
        truckName_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "truck_manufacturer" field.</summary>
    public const int TruckManufacturerFieldNumber = 2;
    private string truckManufacturer_ = "";
    public string TruckManufacturer {
      get { return truckManufacturer_; }
      set {
        truckManufacturer_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "trip_id" field.</summary>
    public const int TripIdFieldNumber = 3;
    private string tripId_ = "";
    public string TripId {
      get { return tripId_; }
      set {
        tripId_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "latitude" field.</summary>
    public const int LatitudeFieldNumber = 4;
    private float latitude_;
    public float Latitude {
      get { return latitude_; }
      set {
        latitude_ = value;
      }
    }

    /// <summary>Field number for the "longitude" field.</summary>
    public const int LongitudeFieldNumber = 5;
    private float longitude_;
    public float Longitude {
      get { return longitude_; }
      set {
        longitude_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as Point);
    }

    public bool Equals(Point other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TruckName != other.TruckName) return false;
      if (TruckManufacturer != other.TruckManufacturer) return false;
      if (TripId != other.TripId) return false;
      if (Latitude != other.Latitude) return false;
      if (Longitude != other.Longitude) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (TruckName.Length != 0) hash ^= TruckName.GetHashCode();
      if (TruckManufacturer.Length != 0) hash ^= TruckManufacturer.GetHashCode();
      if (TripId.Length != 0) hash ^= TripId.GetHashCode();
      if (Latitude != 0F) hash ^= Latitude.GetHashCode();
      if (Longitude != 0F) hash ^= Longitude.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (TruckName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TruckName);
      }
      if (TruckManufacturer.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TruckManufacturer);
      }
      if (TripId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(TripId);
      }
      if (Latitude != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Latitude);
      }
      if (Longitude != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(Longitude);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (TruckName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TruckName);
      }
      if (TruckManufacturer.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TruckManufacturer);
      }
      if (TripId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TripId);
      }
      if (Latitude != 0F) {
        size += 1 + 4;
      }
      if (Longitude != 0F) {
        size += 1 + 4;
      }
      return size;
    }

    public void MergeFrom(Point other) {
      if (other == null) {
        return;
      }
      if (other.TruckName.Length != 0) {
        TruckName = other.TruckName;
      }
      if (other.TruckManufacturer.Length != 0) {
        TruckManufacturer = other.TruckManufacturer;
      }
      if (other.TripId.Length != 0) {
        TripId = other.TripId;
      }
      if (other.Latitude != 0F) {
        Latitude = other.Latitude;
      }
      if (other.Longitude != 0F) {
        Longitude = other.Longitude;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            TruckName = input.ReadString();
            break;
          }
          case 18: {
            TruckManufacturer = input.ReadString();
            break;
          }
          case 26: {
            TripId = input.ReadString();
            break;
          }
          case 37: {
            Latitude = input.ReadFloat();
            break;
          }
          case 45: {
            Longitude = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Response : pb::IMessage<Response> {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Expero.TruckingServiceReflection.Descriptor.MessageTypes[1]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Response(Response other) : this() {
      status_ = other.status_;
    }

    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private int status_;
    public int Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Status != 0) hash ^= Status.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Status != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Status);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Status);
      }
      return size;
    }

    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Status = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Msg : pb::IMessage<Msg> {
    private static readonly pb::MessageParser<Msg> _parser = new pb::MessageParser<Msg>(() => new Msg());
    public static pb::MessageParser<Msg> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Expero.TruckingServiceReflection.Descriptor.MessageTypes[2]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Msg() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Msg(Msg other) : this() {
      helloWorld_ = other.helloWorld_;
    }

    public Msg Clone() {
      return new Msg(this);
    }

    /// <summary>Field number for the "hello_world" field.</summary>
    public const int HelloWorldFieldNumber = 1;
    private string helloWorld_ = "";
    public string HelloWorld {
      get { return helloWorld_; }
      set {
        helloWorld_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as Msg);
    }

    public bool Equals(Msg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HelloWorld != other.HelloWorld) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (HelloWorld.Length != 0) hash ^= HelloWorld.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (HelloWorld.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(HelloWorld);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (HelloWorld.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HelloWorld);
      }
      return size;
    }

    public void MergeFrom(Msg other) {
      if (other == null) {
        return;
      }
      if (other.HelloWorld.Length != 0) {
        HelloWorld = other.HelloWorld;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            HelloWorld = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
